security:
    encoders:
        Teaching\GeneralBundle\Entity\Users:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10
   
    providers:
        administrators:
            entity: { class: TeachingGeneralBundle:Users, property: username }

    firewalls:
        secured_area:
            pattern:   ^/
            anonymous: ~
            form_login: 
                login_path: teaching_homepage
                check_path: login_check
                # Protection to CSRF attacks in form login
                csrf_provider: form.csrf_provider
            logout: 
                path: logout
                target: /
                # To logout session, unless have an error
                invalidate_session: false

    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profesor, roles: ROLE_TEACHER }
        - { path: ^/usuario, roles: ROLE_USER }