services:
    kernel.listener.teaching_general_exception_listener:
      class: Teaching\GeneralBundle\Listener\ExceptionListener
      arguments: [@templating, @kernel]
      tags:
        - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

        